include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - lib/src/ffi/*.dart
    - test/test_data/**

linter:
  rules:
    avoid_print: false
    prefer_single_quotes: true
    directives_ordering: true
