name: arcgis_maps
description: ArcGIS Maps SDK for Flutter
version: 200.5.0+4314
homepage:
publish_to: none

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: '>=3.22.2'

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.2
  http: ^1.2.1
  package_config: ^2.1.0
  async: ^2.11.0
  logger: ^2.0.2
  url_launcher: ^6.2.5
  location: ^5.0.3
  intl: ^0.19.0
  dio: ^5.4.3+1
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_db_store: ^5.1.1
  flutter_web_auth_2: ^3.1.1
  device_info_plus: ^10.1.0
  package_info_plus: ^8.0.0
  sqlite3: ^2.4.3
  sqlite3_flutter_libs: ^0.5.21
  path_provider: ^2.1.3
  path: ^1.9.0
  http_parser: ^4.0.2

dev_dependencies:
  flutter_lints: ^3.0.1

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
        package: com.esri.arcgis_maps
        pluginClass: ArcGISMapsPlugin
      ios:
        ffiPlugin: true
        pluginClass: ArcGISMapsPlugin
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
        pluginClass: ArcGISMapsPlugin
      windows:
        ffiPlugin: true

  assets:
    - assets/
